[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Este documento describe la creación de un DeChat, un chat
descentralizado basado en Solid.
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
El objetivo principal es lograr que los datos no pasen por un servidor
central, si no que cada usuario guarde sus propios datos.
Por tanto el sisema se basará en una arquitectura descentralizada donde el
almacenamiento de datos se separa de la aplicación.

* Los usuarios pueden almacenar sus datos de chat en sus propios pod's.
* A través del chat, los usuarios podrán compartir fotos, vídeos, o cualquier tipo
de archivo con sus amigos.
* Cuando un usuario quiera chatear con un amigo, a este le llegará una notificación.
* Pueden crearse grupos entre usuarios amigos para chatear.
* Habrá chats grupales.

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Objetivos de calidad
|===
|Nr |Calidad |Motivación

|1
|Seguridad
|Column 3, row 1

|2
|Column 2, row 2
|Column 3, row 2

|3
|Column 2, row 3
|Column 3, row 3
|===

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
La siguiente tabla contiene a las personas más importantes e interasadas
en esta aplicación.

.Stakeholders
|===
|Stakeholder |Descripción |Expectativas, motivaciones

|Usuario del chat
|Column 2, row 1
|Column 3, row 1

|La empresa Inrupt
|Column 2, row 2
|Column 3, row 2

|José Emilio Labra Gayo
|Column 2, row 3
|Column 3, row 3

|Equipo de desarrolo
|Column 2, row 4
|Column 3, row 4
|===

****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
