[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
En esta introducción describimos brevemente tanto los usuarios como los sistemas que están implicados en nuestra aplicación de chat descentralizado. Por una parte, el grupo de usuarios está compuesto por los propios que se registran y usan el chat, por los integrantes de este equipo como desarrolladores, y el jefe de proyecto como supervisor. Por otra parte, en el grupo de sistemas tenemos software como Java, JavaScript, Angular, Asciidoctor, Solid...(este grupo de sistemas puede variar a lo largo de la implementación del proyecto).

.Motivation
Aquí describimos el porqué de cada uno de los programas que se encuentran en la lista anteriormente mencionada.

* Java: porque su comodidad de uso por parte de los integrantes del equipo por los amplios conocimientos previos.

* JavaScript: porque es recomendable su uso para aplicaciones con software Solid.

* Angular: porque es un framework de JavaScript que agilizará el proceso de implementación de nuestra aplicación.

* Asciidoctor: porque es el mejor editor de texto para generar la documentación del proyecto mediante ficheros de extensión asciidoc.

* Solid: porque es un software de gestión de datos del cuál el jefe de proyecto nos ha aconsejado su uso.

.Form
Aquí explicamos de una manera más gráfica la información detallada anteriormente.
****
[options="header",cols="1,2,2"]
|===
|Nombre|Tipo de software|Razón de uso
| Java | Lenguaje de programación | Comodidad de uso por amplios conocimientos previos
| JavaScript | Lenguaje de programación | Recomendable su uso para aplicaciones con software Solid
| Angular | Framework de JavaScript | Agilizar el proceso de implementación de nuestro chat
| Asciidoctor | Editor de texto | Mejor editor de texto para generar nuestra documentación mediante ficheros asciidoc
| Solid | Software de gestión de datos | Uso requerido por el jefe de proyecto
|===

=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****

**<Diagram or Table>**

**<optionally: Explanation of external domain interfaces>**

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
