sudo: false
dist: trusty

language: node_js
node_js:
  - 10

addons:
  chrome: stable

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run e2e


after_success:
  - bash <(curl -s https://codecov.io/bash)