dist: trusty
sudo: false

language: node_js
node_js:
   - "10.15"
addons:
  chrome: stable
before_script:
  - npm install 
script: 
  - npm run gulp
  - npm run e2e
after_success:
  - npm run coverage
  - npm run coveralls