dist: trusty
sudo: false

language: node_js
node_js:
   - "10.15"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install 
script: 
  - npm run gulp
  - npm run ng test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
after_success:
  # - npm run cucumber
  - npm run coverage