= DECHAT_ES6B

image:https://travis-ci.org/Arquisoft/DeChat_es6b.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/DeChat_es6b"]
image:https://codecov.io/gh/Arquisoft/dechat_es6b/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_es6b"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_es6b?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es6b&utm_campaign=Badge_Grade"]

== What is DeChat?

DeDhat is a descentralized chat app based on the https://solid.mit.edu/[solid] specifications. Read the documentation for more accurate information about the project.

== Development Team

This project is done by a team of 5 members:

* Carlos Álvarez Rábano.
* Cristina Ruiz de Bucesta Crespo.
* David Carballo Baz.
* Iván Gómez Pinta.
* Sara García Rodríguez.


== Generating documentation

----
gulp
----

Generates documentation in `docs` folder. Previously you need to have installed gulp.js. For this run:

----
npm install gulp-cli -g
----

== Development server

Run development server with:

----
ng serve
----

Navigate to `http://localhost:4200/`. The app will automatically reload if you change any of the source files. If you don't have Angular installed, use Node Package Manager:

----
npm run ng serve
----


== Running unit tests

Run unit tests via https://karma-runner.github.io[Karma]:

----
ng test
----

If you don't have Angular installed, use Node Package Manager:

----
npm run ng test
----
